### ISSUE TITLE
Way to add a title to the modal

### ISSUE THREAD

**Issue by dn5** [electerious/basicModal#6]
Great and super-fast native modal. I'm a back-end programmer and in no way do I have any contact with front-end but this may be a great feature on the lib itself.  
  
If anyone got time to implement it I'll be glad to spread your code. On other hand, I may try to do it myself in the meantime.  
  
* Add implementation of the title to the modal  
  
Kind regards!

**Comment by electerious** [comment]
The `body`-key allows you to add any kind of HTML to the modal. Here's an example:

```js
basicModal.show({
	body: '<div class="title">Modal Title</div><p>This is a dead-simple alert modal!<br>The message can be filled with anything you want.</p>',
	buttons: {
		action: {
			title: 'Dismiss',
			fn: basicModal.close
		}
	}
})
```

In this case you can use the class `title` to style your title. This requires a few lines of CSS, but shouldn't be too hard. Make sure you remove the padding from `.basicModal__content`, so the title can start at the top.
