### ISSUE TITLE
Parse selects when getting values from the modal

### ISSUE THREAD

**Issue by BrunoBernardino** [electerious/basicModal#7]
The [`getValues()`](https://github.com/electerious/basicModal/blob/master/src/scripts/main.js#L114) function only parses inputs. Is there a reason for it to not parse selects?

I can make a PR for it, if there's no philosophical opposition :)

**Comment by electerious** [comment]
That's a good idea :) I will add it by time or you can open a PR.

**Comment by BrunoBernardino** [comment]
PR made. :)

**Comment by electerious** [comment]
Added a demo and made some small code adjustment. This feature is now included in version 3.3.

**Comment by BrunoBernardino** [comment]
Awesome! I don't see bower's been upgraded, though (only npm)? Looking at https://github.com/electerious/basicModal/blob/master/bower.json and https://github.com/electerious/basicModal/tags

**Comment by electerious** [comment]
Fixed! :)

**Comment by BrunoBernardino** [comment]
Great stuff!
